### ISSUE TITLE
Copy from furry panel generation throw "ArgumentNullException" 

### ISSUE THREAD

**Issue by Miiraak** [Miiraak/CharGen#1]
System.ArgumentNullException: Value cannot be null. (Parameter 'text')
   at System.Windows.Forms.ArgumentValidation.ThrowIfNullOrEmpty(String argument, String paramName)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at CharGen.FormOutput.buttonCopy_Click(Object sender, EventArgs e) in C:\[...]\CharGen\Form5.cs:line 24
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by Miiraak** [comment]
_patched_
